# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7c8b52aaec3ef127021ae5821778154eb2e5b51cd9900b5d84b13d4baecd74f1bf34f44b63462cb36f5516bfc15fec8a2f09b2650de0a0eef9fe0a81297d25

test:
  secret_key_base: 15469a4a12cdd259bc6cfcdcfc8127d84992695c7ebe877998bc1bd6814dd739ce065eac67cb485d438f71cfb9387650c96c2f0069da531c97de359e3e5aafd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
